DROP database IF EXISTS address_book;
CREATE database address_book;
USE address_book;

CREATE TABLE contact (
id INT(11) NOT NULL AUTO_INCREMENT,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
patronymic VARCHAR(50) DEFAULT NULL,
birthdate DATE NOT NULL,
phone VARCHAR(50) NOT NULL UNIQUE, 
email VARCHAR(50) DEFAULT NULL UNIQUE,
PRIMARY KEY(id)
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE address (
contactid INT(11) NOT NULL AUTO_INCREMENT,
postcode VARCHAR(50) NOT NULL,
country  VARCHAR(50) NOT NULL,
city VARCHAR(50) NOT NULL,
street VARCHAR(50) DEFAULT NULL,
house VARCHAR(50) NOT NULL,
block VARCHAR(50) DEFAULT NULL,
flat VARCHAR(50) DEFAULT NULL,
PRIMARY KEY(contactid),
FOREIGN KEY(`contactid`) REFERENCES contact (id) ON DELETE CASCADE
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE section (
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(50) NOT NULL
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE contact_section (
id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
contactid INT(11) NOT NULL,
sectionid INT(11) NOT NULL,
UNIQUE KEY contact_section(contactid, sectionid),
FOREIGN KEY (contactid) REFERENCES contact(id) ON DELETE CASCADE,
FOREIGN KEY (sectionid) REFERENCES section(id) ON DELETE CASCADE
)
ENGINE=INNODB DEFAULT CHARSET=utf8;

/*add default sections script*/

